name: Auto Merge Daily Leetcode branch to Main

on:
  push:
    branches:
      - 'daily-leetcode'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Garante que todas as branches sejam buscadas

      - name: List branches
        run: git branch -r  # Lista as branches remotas para depuração

      - name: Set Git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Checkout main branch
        run: git checkout main

      - name: Merge daily-leetcode to main
        run: |
          git merge --no-ff daily-leetcode
          git push origin main

