name: Auto Merge Daily to Main

on:
  push:
    branches:
      - 'daily-leetcode'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Checkout default branch
        run: |
          git fetch origin
          git checkout $(git rev-parse --abbrev-ref origin/HEAD | sed 's@^origin/@@')
  
      - name: Merge daily-leetcode to default branch
        run: |
          git merge --no-ff daily-leetcode
          git push origin $(git rev-parse --abbrev-ref HEAD)
